"""Deck health and recommendation output packet models."""

from .models import (
    DeckHealthFinding,
    DeckHealthPacket,
    EvidenceExplanationPacket,
    PackageGapPacket,
    RecommendationCandidatePacket,
    RecommendationOutputBuildError,
    RecommendationOutputBundle,
    RecommendationOutputOptions,
    ReplacementSuggestionPacket,
    build_deck_health_packet,
    build_evidence_explanation_packet,
    build_package_gap_packet,
    build_recommendation_candidate_packet,
    build_recommendation_output_bundle,
    build_replacement_suggestion_packet,
    deck_health_packet_to_dict,
    evidence_explanation_packet_to_dict,
    package_gap_packet_to_dict,
    recommendation_candidate_packet_to_dict,
    recommendation_output_bundle_to_dict,
    replacement_suggestion_packet_to_dict,
    validate_recommendation_output_bundle,
)
from .reporting import (
    RecommendationReportDocument,
    RecommendationReportOptions,
    RecommendationReportSection,
    build_recommendation_report_document,
    recommendation_report_document_to_dict,
    recommendation_report_document_to_markdown,
    validate_recommendation_report_document,
)
from .writers import (
    RecommendationReportWriteError,
    RecommendationReportWriteOptions,
    RecommendationReportWriteResult,
    write_recommendation_report_files,
)


__all__ = [
    "DeckHealthFinding",
    "DeckHealthPacket",
    "EvidenceExplanationPacket",
    "PackageGapPacket",
    "RecommendationCandidatePacket",
    "RecommendationOutputBuildError",
    "RecommendationOutputBundle",
    "RecommendationOutputOptions",
    "RecommendationReportDocument",
    "RecommendationReportOptions",
    "RecommendationReportSection",
    "RecommendationReportWriteError",
    "RecommendationReportWriteOptions",
    "RecommendationReportWriteResult",
    "ReplacementSuggestionPacket",
    "build_deck_health_packet",
    "build_evidence_explanation_packet",
    "build_package_gap_packet",
    "build_recommendation_candidate_packet",
    "build_recommendation_output_bundle",
    "build_replacement_suggestion_packet",
    "deck_health_packet_to_dict",
    "evidence_explanation_packet_to_dict",
    "package_gap_packet_to_dict",
    "recommendation_candidate_packet_to_dict",
    "recommendation_output_bundle_to_dict",
    "recommendation_report_document_to_dict",
    "recommendation_report_document_to_markdown",
    "replacement_suggestion_packet_to_dict",
    "build_recommendation_report_document",
    "write_recommendation_report_files",
    "validate_recommendation_report_document",
    "validate_recommendation_output_bundle",
]
