"""Deterministic analytics built from canonical Codie records."""

from .foundations import AnalyticsBuildResult, AnalyticsFoundationBuilder
from .innovation import (
    InnovationFilter,
    InnovationObservation,
    InnovationSnapshotSpec,
    InnovationSignal,
    PersistedInnovationSnapshot,
    config_hash,
    config_json,
    detect_innovations,
    detect_innovations_from_repository,
    innovation_snapshot_item_row,
    innovation_snapshot_run_row,
    innovation_observations_from_rows,
    innovation_evidence_line,
    persist_innovation_snapshot,
)
from .weights import (
    AnalyticsError,
    decklist_completeness_weight,
    event_size_weight,
    final_entry_weight,
    normalize_time_window,
    placement_weight,
    recency_weight,
    source_confidence_weight,
)

__all__ = [
    "AnalyticsBuildResult",
    "AnalyticsError",
    "AnalyticsFoundationBuilder",
    "InnovationFilter",
    "InnovationObservation",
    "InnovationSnapshotSpec",
    "InnovationSignal",
    "PersistedInnovationSnapshot",
    "config_hash",
    "config_json",
    "detect_innovations",
    "detect_innovations_from_repository",
    "decklist_completeness_weight",
    "event_size_weight",
    "final_entry_weight",
    "innovation_snapshot_item_row",
    "innovation_snapshot_run_row",
    "innovation_evidence_line",
    "innovation_observations_from_rows",
    "normalize_time_window",
    "persist_innovation_snapshot",
    "placement_weight",
    "recency_weight",
    "source_confidence_weight",
]
