"""User deck import and analysis-session helpers."""

from .analysis_input import (
    UserDeckAnalysisCard,
    UserDeckAnalysisInput,
    UserDeckAnalysisInputError,
    build_user_deck_analysis_input,
)
from .deck_memory import (
    DeckMemoryAnalysisSummary,
    DeckMemoryCard,
    DeckMemoryDetail,
    DeckMemoryFilters,
    DeckMemoryReadError,
    DeckMemorySessionSummary,
    DeckMemorySummary,
    get_deck_memory_detail,
    list_deck_memory,
)
from .evidence_comparison import (
    UserDeckEvidenceCandidate,
    UserDeckEvidenceComparison,
    UserDeckEvidenceComparisonRow,
    compare_user_deck_to_evidence,
)
from .immutable_snapshots import (
    IMMUTABLE_DECK_SNAPSHOT_VERSION,
    DeckSnapshotAnalysisRef,
    DeckSnapshotCard,
    DeckSnapshotPrivacyPolicy,
    DeckSnapshotReplayMetadata,
    DeckSnapshotSourceRef,
    DeckSnapshotWarning,
    ImmutableDeckSnapshot,
    ImmutableDeckSnapshotError,
    ImmutableDeckSnapshotOptions,
    build_immutable_deck_snapshot,
    immutable_deck_snapshot_to_dict,
    validate_immutable_deck_snapshot,
)
from .importer import (
    ParsedUserDeck,
    ParsedUserDeckCard,
    UserDeckImportError,
    UserDeckImportResult,
    UserDeckImporter,
    parse_user_deck_text,
)
from .saved_analysis import SavedUserDeckAnalysisResult, save_user_deck_comparison_analysis
from .saved_analysis_listing import (
    SavedAnalysisDetail,
    SavedAnalysisReadError,
    SavedAnalysisSummary,
    get_saved_user_deck_analysis,
    list_saved_user_deck_analyses,
)

__all__ = [
    "ParsedUserDeck",
    "ParsedUserDeckCard",
    "DeckMemoryAnalysisSummary",
    "DeckMemoryCard",
    "DeckMemoryDetail",
    "DeckMemoryFilters",
    "DeckMemoryReadError",
    "DeckMemorySessionSummary",
    "DeckMemorySummary",
    "DeckSnapshotAnalysisRef",
    "DeckSnapshotCard",
    "DeckSnapshotPrivacyPolicy",
    "DeckSnapshotReplayMetadata",
    "DeckSnapshotSourceRef",
    "DeckSnapshotWarning",
    "IMMUTABLE_DECK_SNAPSHOT_VERSION",
    "ImmutableDeckSnapshot",
    "ImmutableDeckSnapshotError",
    "ImmutableDeckSnapshotOptions",
    "UserDeckAnalysisCard",
    "UserDeckAnalysisInput",
    "UserDeckAnalysisInputError",
    "UserDeckEvidenceCandidate",
    "UserDeckEvidenceComparison",
    "UserDeckEvidenceComparisonRow",
    "UserDeckImportError",
    "UserDeckImportResult",
    "UserDeckImporter",
    "SavedUserDeckAnalysisResult",
    "SavedAnalysisDetail",
    "SavedAnalysisReadError",
    "SavedAnalysisSummary",
    "build_user_deck_analysis_input",
    "build_immutable_deck_snapshot",
    "compare_user_deck_to_evidence",
    "get_deck_memory_detail",
    "get_saved_user_deck_analysis",
    "immutable_deck_snapshot_to_dict",
    "list_deck_memory",
    "list_saved_user_deck_analyses",
    "parse_user_deck_text",
    "save_user_deck_comparison_analysis",
    "validate_immutable_deck_snapshot",
]
