"""Recommendation statistics primitives."""

from .evidence import (
    EvidenceBundle,
    EvidenceItem,
    EvidenceStackSummary,
    build_evidence_bundle,
    evidence_stack_summary,
    validate_claim_text,
)
from .generation import (
    RecommendationCandidatePacket,
    RecommendationCandidateSource,
    RecommendationGenerationConfig,
    build_candidate_packet,
    candidate_sources_from_staples_report,
    generate_candidate_packets,
)
from .observations import staple_observations_from_canonical_rows
from .persistence import (
    PersistedRecommendationRun,
    RecommendationRunSpec,
    persist_recommendation_packets,
    recommendation_candidate_row,
    recommendation_run_row,
)
from .reports import (
    CandidateAuditIssue,
    CandidateAuditReport,
    build_candidate_audit_report,
    candidate_explanation_lines,
    validate_candidate_explanation_lines,
)
from .scoring import (
    RecommendationCandidateDraft,
    RecommendationScoreBreakdown,
    RecommendationScoreInput,
    ScoreComponent,
    build_recommendation_candidate_draft,
    low_sample_penalty,
    normalize_candidate_type,
    score_recommendation_candidate,
)
from .statistics import (
    ConfidenceRating,
    FrequencyStats,
    GenericStapleProfile,
    clamp,
    confidence_rating,
    frequency_stats,
    generic_staple_profile,
    inclusion_rate,
    jaccard_similarity,
    lift_score,
    safe_rate,
    weighted_inclusion_rate,
    weighted_jaccard_similarity,
)
from .staples import (
    CommanderStaplesReport,
    StapleObservation,
    StapleReportRow,
    build_commander_staples_report,
)

__all__ = [
    "ConfidenceRating",
    "CommanderStaplesReport",
    "CandidateAuditIssue",
    "CandidateAuditReport",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceStackSummary",
    "FrequencyStats",
    "GenericStapleProfile",
    "RecommendationCandidateDraft",
    "RecommendationCandidatePacket",
    "RecommendationCandidateSource",
    "RecommendationGenerationConfig",
    "RecommendationRunSpec",
    "RecommendationScoreBreakdown",
    "RecommendationScoreInput",
    "ScoreComponent",
    "StapleObservation",
    "StapleReportRow",
    "PersistedRecommendationRun",
    "build_candidate_packet",
    "build_candidate_audit_report",
    "build_evidence_bundle",
    "build_commander_staples_report",
    "build_recommendation_candidate_draft",
    "candidate_explanation_lines",
    "candidate_sources_from_staples_report",
    "clamp",
    "confidence_rating",
    "evidence_stack_summary",
    "frequency_stats",
    "generate_candidate_packets",
    "generic_staple_profile",
    "inclusion_rate",
    "jaccard_similarity",
    "lift_score",
    "low_sample_penalty",
    "persist_recommendation_packets",
    "recommendation_candidate_row",
    "recommendation_run_row",
    "normalize_candidate_type",
    "safe_rate",
    "score_recommendation_candidate",
    "staple_observations_from_canonical_rows",
    "validate_claim_text",
    "validate_candidate_explanation_lines",
    "weighted_inclusion_rate",
    "weighted_jaccard_similarity",
]
