CREATE TABLE cards (
    scryfall_id TEXT PRIMARY KEY,
    oracle_id TEXT,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    mana_cost TEXT,
    mana_value REAL,
    type_line TEXT,
    oracle_text TEXT,
    colors_json TEXT,
    color_identity_json TEXT,
    legalities_json TEXT,
    produced_mana_json TEXT,
    keywords_json TEXT,
    layout TEXT,
    card_faces_json TEXT,
    image_uris_json TEXT,
    prices_json TEXT,
    set_code TEXT,
    collector_number TEXT,
    rarity TEXT,
    released_at TEXT,
    is_reserved INTEGER DEFAULT 0,
    is_digital INTEGER DEFAULT 0,
    is_legal_commander INTEGER DEFAULT 0,
    is_commander_candidate INTEGER DEFAULT 0,
    raw_json TEXT NOT NULL,
    imported_at TEXT NOT NULL
);

CREATE TABLE commanders (
    commander_id INTEGER PRIMARY KEY AUTOINCREMENT,
    scryfall_id TEXT NOT NULL,
    oracle_id TEXT,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    color_identity_json TEXT NOT NULL,
    is_partner INTEGER DEFAULT 0,
    is_background_compatible INTEGER DEFAULT 0,
    is_doctor_companion INTEGER DEFAULT 0,
    is_friends_forever INTEGER DEFAULT 0,
    legal_status TEXT,
    raw_source TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(scryfall_id) REFERENCES cards(scryfall_id)
);
