CREATE INDEX idx_cards_oracle_id ON cards(oracle_id);
CREATE INDEX idx_cards_normalized_name ON cards(normalized_name);
CREATE INDEX idx_cards_color_identity ON cards(color_identity_json);
CREATE INDEX idx_commanders_normalized_name ON commanders(normalized_name);
CREATE INDEX idx_provider_objects_lookup ON provider_objects(provider, object_type, provider_id);
CREATE INDEX idx_source_events_provider_event ON source_events(provider, provider_event_id);
CREATE INDEX idx_source_events_canonical ON source_events(canonical_event_id);
CREATE INDEX idx_source_decks_event ON source_decks(source_event_id);
CREATE INDEX idx_source_decks_canonical ON source_decks(canonical_deck_id);
CREATE INDEX idx_source_deck_cards_deck ON source_deck_cards(source_deck_id);
CREATE INDEX idx_source_deck_cards_oracle ON source_deck_cards(oracle_id);
CREATE INDEX idx_canonical_events_dedupe ON canonical_events(dedupe_key);
CREATE INDEX idx_canonical_decks_hash ON canonical_decks(deck_hash);
CREATE INDEX idx_canonical_deck_cards_deck ON canonical_deck_cards(canonical_deck_id);
CREATE INDEX idx_canonical_deck_cards_oracle ON canonical_deck_cards(oracle_id);
CREATE INDEX idx_event_deck_entries_event ON event_deck_entries(canonical_event_id);
CREATE INDEX idx_event_deck_entries_deck ON event_deck_entries(canonical_deck_id);
CREATE INDEX idx_primer_registry_commander ON primer_registry(commander_key, partner_key);
CREATE INDEX idx_commander_registry_signature ON commander_registry(commander_signature);
CREATE INDEX idx_alias_registry_target_name ON alias_registry(normalized_target_name);
CREATE INDEX idx_alias_registry_oracle ON alias_registry(target_oracle_id);
CREATE INDEX idx_archetype_label_registry_label ON archetype_label_registry(normalized_label);
CREATE INDEX idx_combo_cards_oracle ON combo_cards(oracle_id);
CREATE INDEX idx_package_cards_package ON package_cards(package_id);
CREATE INDEX idx_card_performance_oracle_window ON card_performance_metrics(oracle_id, time_window, window_end_date);
CREATE INDEX idx_evidence_counts_entity ON evidence_counts(entity_type, entity_id);
CREATE INDEX idx_regional_commander_lookup ON regional_commander_metrics(region_code, country_code, commander_signature);
CREATE INDEX idx_regional_card_lookup ON regional_card_metrics(region_code, country_code, oracle_id);
CREATE INDEX idx_simulation_results_batch ON simulation_batch_results(batch_id);
CREATE INDEX idx_user_deck_cards_deck ON user_deck_cards(user_deck_id);
CREATE INDEX idx_analysis_sessions_deck_hash ON analysis_sessions(deck_hash);
